# Generated by Django 4.2.3 on 2025-10-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namespace",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="namespace",
            unique_together={("organization", "name")},
        ),
    ]
